name: streamlit_app

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: sechadesu/streamlitweb:latest
    ports:
      - 11443:8501
    expose:
      - 22
    secrets:
      - streamlit
      - input
    volumes:
      - shared-volume:/data
    depends_on:
      - worker

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    #image: sechadesu/streamlitworker:latest
    expose:
      - 22
    secrets:
      - api-key
    volumes:
      - shared-volume:/server/data

secrets:
  api-key:
    file: ./server/key.txt
  streamlit:
    file: ./server/streamlit.txt
  input:
    file: ./input.txt

volumes:
  shared-volume:
