name: streamlit_app
version: "1.0"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FINN: /run/secrets/api-key
    ports:
      - 8501:8501
    expose:
      - "3000"
    secrets:
      - api-key
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000

secrets:
  api-key:
    file: ./server/key.txt
