name: streamlit_app

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    expose:
      - 22
    volumes:
      - shared-volume:/data

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
      secrets:
        - api-key
    expose:
      - 22
    secrets:
      - api-key
    volumes:
      - shared-volume:/server/data
    #env_file:
    #  - ./server/.env

secrets:
  api-key:
    file: ./server/key.txt

volumes:
  shared-volume:
