name: streamlit_app

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    expose:
      - "3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      secrets:
        - api-key
    expose:
      - "3000"
    secrets:
      - api-key
    volumes:
      - shared-volume:/server/data

secrets:
  api-key:
    file: ./server/key.txt

volumes:
  shared-volume:
