[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#FFD700"
font = "sans serif"

[server]
port = 8502
headless = true

[browser]
serverAddress = "datafeeddemo.seanbrown.org"
serverPort = 8502